
summaryTimeout: 5
email: halterbreaksuit169@abcxyza.com
password: 12qwaszxCV@
otp: ""

uploadFileTitleName: Open
uploadFileEditTextId: Edit1

loginDoneId: //span[text()='Settings']
otpId: //input[@id='auth-mfa-otpcode']
rememberBrowserId: auth-mfa-remember-device 
signInOtpButttonId: auth-signin-button

webDataPath: chrome-data
showInterface: true
productDataPath: productData/
productSizePath: productSize/
productDonePath: DONE

loginUrl: https://sellercentral.amazon.com/signin
emailId: //input[@type='email']
rememberLoginId: //input[@name='rememberMe']

passwordId: //input[@type='password']

loginButtonId: //input[@type='submit']

inventoryUrl: https://sellercentral.amazon.com/inventory/ref=xx_invmgr_dnav_xx
editProductDropdownId: //button[@id='a-autoid-5-announce']
copyListItemId: //a[@id='dropdown1_2']
copyListItemBackupId: //a[@id='dropdown1_3']
productTitleId: //input[@id='item_name']  

image1Id: //span[@class='a-size-base a-color-tertiary a-text-normal']
imageTabId: "//div[@id='hub-spoke-image-menu-item']"
image2Id: //div[@id='pt1_image_url-wrapper']//div[@class='ilui-image-select-container']
image3Id: //div[@id='pt2_image_url-wrapper']//div[@class='ilui-image-select-container']
image1UploadProgressId: (//span[@class='percentage'])[1]
image2UploadProgressId: (//span[@class='percentage'])[2]
image3UploadProgressId: (//span[@class='percentage'])[3]
saveButtonId: //span[@id='ilui-publish-button']//input[@class='a-button-input']

uploadImageDelayTime: 1
uploadImageTimeout: 50
saveTimeout: 3
waitOtpTimeout: 60